src/Entity/Director.php
<?php

namespace App\Entity;

use App\Repository\DirectorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DirectorRepository::class)
 */
class Director
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $lastname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $country;

    /**
     * @ORM\OneToMany(targetEntity=Movie::class, mappedBy="director")
     */
    private $movies;

    /**
     * @ORM\Column(type="boolean", options={"default": "1"})
     */
    private $active;

    public function __construct()
    {
        $this->movies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(?\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return Collection<int, Movie>
     */
    public function getMovies(): Collection
    {
        return $this->movies;
    }

    public function addMovie(Movie $movie): self
    {
        if (!$this->movies->contains($movie)) {
            $this->movies[] = $movie;
            $movie->setDirector($this);
        }

        return $this;
    }

    public function removeMovie(Movie $movie): self
    {
        if ($this->movies->removeElement($movie)) {
            // set the owning side to null (unless already changed)
            if ($movie->getDirector() === $this) {
                $movie->setDirector(null);
            }
        }

        return $this;
    }

    public function getFullname(): string
    {
        return $this->getFirstname(). ' ' . $this->getLastname();
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }
}

src/Controller/DirectorController.php
<?php

namespace App\Controller;

use App\Entity\Director;
use App\Repository\DirectorRepository;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/director", name="director_")
 */
class DirectorController extends AbstractController
{
    /**
     * @Route("", name="index")
     */
    public function index(DirectorRepository $directorRepository): Response
    {
        $directors = $directorRepository->findAll();

        return $this->render('director/index.html.twig', [
            'directors' => $directors
        ]);
    }

    /**
     * @Route("/remove/{id}/{token}", name="remove")
     */
    public function remove(Director $director, string $token, DirectorRepository $directorRepository, LoggerInterface $logger): Response
    {
        if(!$this->isCsrfTokenValid('remove_director_'.$director->getFullname(), $token)) {
            $logger->alert("Attention tentative d'intrusion sans token valide !");
            throw $this->createNotFoundException(); // 404
        }

        $directorRepository->remove($director, true);
        $this->addFlash('success', 'Réalisateur supprimé.');

        return $this->redirectToRoute('director_index');
    }


    /**
     * @Route("/{id}", name="detail")
     */
    public function detail(int $id, DirectorRepository $directorRepository): Response
    {
        // $this->isCsrfTokenValid();
        /*$token = new CsrfToken('tokenId', 'delete-movie');
        dump($token->getValue());*/

        $director = $directorRepository->findDirectorWithMovies($id);

        return $this->render('director/detail.html.twig', [
            'director' => $director
        ]);
    }
}

templates/director/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ director.fullname }}{% endblock %}

{% block body %}
    <h1>{{ director.fullname }}</h1>

    {% set diff = date().diff(director.birthday) %}
    <p><b>Age</b>: {{ diff.y }} ans</p>

    <p><b>Filmographie</b></p>
    <ul>
    {% for movie in director.movies %}
        <li>{{ movie.title }} <small>({{ movie.releaseDate | date('Y') }})</small></li>
    {% endfor %}
    </ul>
{% endblock %}

templates/director/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Réalisateurs{% endblock %}

{% block body %}

    <h2>Liste des Réalisateurs</h2>

    <table class="table">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Date naissance</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for director in directors %}
            <tr>
                <td>{{ director.fullname }}</td>
                <td>{{ director.birthday | format_date }}</td>
                <td>
                    <div class="d-grid">
                        <a href="{{ path('director_remove', {'id': director.id, 'token': csrf_token('remove_director_' ~ director.fullname)}) }}"
                           class="btn btn-block btn-sm btn-outline-danger">Supprimer</a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}